"""What `python -m build` hands to `twine upload` must be an explicit allowlist.

Owner decision D1, 2026-09-24. Until then `pyproject.toml` configured only the
WHEEL, so the source archive (sdist) shipped every file git does not ignore.
Measured 2026-09-25 on 2.4.144: 369 files, including `scripts/harness/`,
`tools/diag/`, `tests/`, `CLAUDE.md` and `LESSONS.md`. GitHub publishes those on
purpose; PyPI did not need them, and a PyPI upload cannot be withdrawn — 122
older sdists are still served there, the pre-purge ones carrying the material
the 2026-08-06 history purge removed from git.

`tests/test_public_repo_hygiene.py` cannot see this: it reads `git ls-files`,
and the archive is built from the working tree by a different tool with its own
selection rules. So this test builds the real archives and reads what is inside.

The allowlist below is deliberately a SECOND copy of the one in
`pyproject.toml` (`[tool.hatch.build.targets.sdist] only-include`). If it read
the config, widening the config would widen the test with it.
"""

from __future__ import annotations

import importlib.util
import os
import re
import shutil
import subprocess
import tarfile
import zipfile
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent

# Root files allowed in the sdist, besides the package's own modules.
SDIST_ROOT_FILES = {
    "pyproject.toml",
    "PKG-INFO",  # generated by the build backend
    "LICENSE",
    # The `readme` in pyproject.toml; it becomes the PyPI project page, and the
    # wheel cannot be built from the sdist without it.
    "README.md",
    # Hatchling copies this into every sdist unconditionally, so a rebuild from
    # the archive honours the same ignores. It is already public on GitHub; the
    # guard rates its content 0 blocking (6 suspect: names of IGNORED categories).
    ".gitignore",
}

WHEEL_METADATA = re.compile(
    r"^docpluck-[^/]+\.dist-info/"
    r"(METADATA|WHEEL|RECORD|entry_points\.txt|licenses/LICENSE)$"
)


def _is_module(rel: str) -> bool:
    return rel.startswith("docpluck/") and rel.endswith(".py")


def sdist_violations(rel_names: list[str]) -> list[str]:
    return sorted(
        r for r in rel_names if not (_is_module(r) or r in SDIST_ROOT_FILES)
    )


def wheel_violations(names: list[str]) -> list[str]:
    return sorted(
        n for n in names if not (_is_module(n) or WHEEL_METADATA.match(n))
    )


def _require_backend() -> None:
    # A missing backend is a FAILURE, not a skip: a skipped gate reads as green
    # while the archive goes out unchecked.
    if importlib.util.find_spec("hatchling") is None:
        pytest.fail(
            "hatchling is not installed, so the distribution cannot be built "
            "and checked. Install the dev extras: pip install -e .[dev]"
        )


def _build(target: str, src: Path, out: Path) -> Path:
    """Call the backend's PEP 517 hook in-process — the same entry point
    `python -m build` calls. In-process because a fresh interpreter cost ~9 s
    per build on this machine (measured 2026-09-25), and there are four."""
    from hatchling import build as backend

    out.mkdir(parents=True, exist_ok=True)
    hook = backend.build_sdist if target == "sdist" else backend.build_wheel
    # The hooks build the project in the current directory, by specification.
    prev = os.getcwd()
    os.chdir(src)
    try:
        name = hook(str(out))
    finally:
        os.chdir(prev)
    return out / name


def _sdist_rel_names(sdist: Path) -> list[str]:
    with tarfile.open(sdist) as tf:
        names = [m.name for m in tf.getmembers() if m.isfile()]
    # Every entry sits under one top-level "docpluck-<version>/" directory.
    roots = {n.split("/", 1)[0] for n in names}
    assert len(roots) == 1, f"sdist has more than one top-level directory: {roots}"
    return [n.split("/", 1)[1] for n in names]


@pytest.fixture(scope="module")
def built(tmp_path_factory):
    """The real sdist from this tree, and the wheel built FROM that sdist —
    the same order `python -m build` uses before `twine upload dist/*`."""
    _require_backend()
    tmp = tmp_path_factory.mktemp("dist")
    sdist = _build("sdist", REPO, tmp / "sdist")
    unpacked = tmp / "unpacked"
    with tarfile.open(sdist) as tf:
        # `filter` arrived in 3.10.12 / 3.11.4; requires-python allows older.
        if hasattr(tarfile, "data_filter"):
            tf.extractall(unpacked, filter="data")
        else:
            tf.extractall(unpacked)
    (src,) = unpacked.iterdir()
    wheel = _build("wheel", src, tmp / "wheel")
    return sdist, wheel


def test_sdist_ships_only_allowlisted_files(built):
    sdist, _ = built
    bad = sdist_violations(_sdist_rel_names(sdist))
    assert not bad, (
        "the source archive would publish files that are not on its allowlist. "
        "PyPI keeps every upload forever. Narrow `only-include` in "
        "pyproject.toml, or — if the file is genuinely meant for PyPI — add it "
        "to SDIST_ROOT_FILES here with the reason:\n  " + "\n  ".join(bad)
    )


def test_sdist_ships_every_tracked_module_and_nothing_untracked(built):
    """The positive half. An archive that shipped nothing would pass the test
    above; this one requires the package itself to be there, exactly as git
    tracks it — so a scratch module sitting untracked in `docpluck/` fails too,
    because `twine upload` would publish it."""
    sdist, _ = built
    shipped = {r for r in _sdist_rel_names(sdist) if _is_module(r)}
    tracked = set(
        subprocess.run(
            ["git", "ls-files", "docpluck/*.py"], cwd=REPO,
            capture_output=True, text=True, check=True,
        ).stdout.splitlines()
    )
    assert "docpluck/__init__.py" in tracked, "git ls-files returned no package"
    assert shipped == tracked, (
        f"missing from sdist: {sorted(tracked - shipped)}\n"
        f"in sdist but not tracked: {sorted(shipped - tracked)}"
    )


def test_wheel_built_from_the_sdist_ships_only_the_package(built):
    _, wheel = built
    names = zipfile.ZipFile(wheel).namelist()
    assert "docpluck/__init__.py" in names
    bad = wheel_violations(names)
    assert not bad, "the wheel carries unexpected files:\n  " + "\n  ".join(bad)


# ── Two-sided: the same checks, on a tree with files planted in it ──────────


def _planted_tree(dst: Path) -> Path:
    shutil.copytree(
        REPO / "docpluck", dst / "docpluck",
        ignore=shutil.ignore_patterns("__pycache__", "*.pyc"),
    )
    for rel in ("pyproject.toml", "LICENSE", "README.md", ".gitignore"):
        (dst / rel).parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(REPO / rel, dst / rel)
    # Four non-allowlisted files: three in places the old config shipped, one
    # INSIDE the package directory, which `only-include` cannot keep out.
    planted = {
        "tools/planted_probe.py": "x = 1\n",
        "scripts/harness/planted_probe.py": "x = 1\n",
        # A root-level note. Not CLAUDE.md: since 2.4.146 .gitignore excludes that
        # file, and hatchling honours .gitignore, so it could not reach the archive
        # under either config and the control would prove nothing.
        "PLANTED_NOTES.md": "planted\n",
        "docpluck/planted_notes.md": "planted\n",
    }
    for rel, body in planted.items():
        (dst / rel).parent.mkdir(parents=True, exist_ok=True)
        (dst / rel).write_text(body, encoding="utf-8")
    return dst


def test_control_a_file_planted_inside_the_package_is_caught(tmp_path):
    """With the real config, the three outside files stay out — and the one
    planted inside `docpluck/` gets through the config and is caught here."""
    _require_backend()
    src = _planted_tree(tmp_path / "src")
    names = _sdist_rel_names(_build("sdist", src, tmp_path / "out"))
    assert sdist_violations(names) == ["docpluck/planted_notes.md"]


def test_control_the_old_config_would_have_failed(tmp_path):
    """Remove the sdist section (the config every release up to 2.4.144 used):
    the gate must go red on the planted files."""
    _require_backend()
    src = _planted_tree(tmp_path / "src")
    py = src / "pyproject.toml"
    text = py.read_text(encoding="utf-8")
    line = re.search(r"(?m)^only-include = .*\n", text)
    assert line is not None, "control cannot find only-include to remove"
    py.write_text(text.replace(line.group(0), ""), encoding="utf-8")

    bad = sdist_violations(_sdist_rel_names(_build("sdist", src, tmp_path / "out")))
    for rel in ("tools/planted_probe.py", "scripts/harness/planted_probe.py",
                "PLANTED_NOTES.md", "docpluck/planted_notes.md"):
        assert rel in bad, f"{rel} was not flagged; flagged: {bad}"
